### ISSUE TITLE
Are there alternative formats for the command line result

### ISSUE THREAD

**Issue by skytreader** [geneseframework/complexity#60]
I ran the tool as `genese cpx -c ./src/` but it only returned the top 30 or so most-complex parts in the specified code directory, and with a further "per method" field. What I want to do (in order of importance to me at the moment) is:

- generate a report for _all_ files in the specified directory.
- generate a score on a per file basis, rather than additonally consider the method.

Is it possible to do this right now? If not, are you open for this contribution? (And if not, would you kindly point me to which part of the code base could I modify anyway, because then I would still like to modify it myself, I just won't bother upstream with my changes.)

**Comment by geneseframework** [comment]
Hi,
at first, we are open for new contributions. We put this project in open-source because it is great to add new features coming from the ideas of other developers. If you want, you can contact me directly by email, it will be easier : https://github.com/gillesfabre34

About your questions : 

* generate a report for all files in the specified directory.

When you say "all" files, do you mean "recursively" ?

*  generate a score on a per file basis, rather than additonally consider the method.

I suppose that you saw that you already have a score per file, so could you explain more precisely what you'd like to have ?

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/63037808/170816606-ce13df3e-9a98-49b4-99e5-1a2b8ab2e33f.png">

**Comment by skytreader** [comment]
I think describing what I'm doing would be more illustrative. So the reason why I want to do the two things I specified is because I am compiling a spreadsheet report. I mean, the generated HTML looks really pretty, don't get me wrong, but I just need to present the data in a different way, for a non-dev audience.

To that end, it would be really useful for me if the report was printed on the console and I could just copy-paste to my spreadsheet (or even write a script, transform it to CSV).

So, yes, by "all files", I mean something like out of a recursive crawl of the directory I specified. Something like [Python's `os.walk`](https://medium.com/upsolve-digest/how-to-recursively-crawl-folders-using-python-691250de2f1) would come up with.

At the moment, running `genese cpx -c ./src/` on this project directory returns only a report of around 30 files when I know the project has more. I presume the result printed is sorted in descending order so I guess the "missing" files just didn't score high enough. I'd like them on the report all the same.

> I suppose that you saw that you already have a score per file, so could you explain more precisely what you'd like to have ?

As I stated above, I just need the console output to display this too, for my copy-pasting convenience.

**Comment by geneseframework** [comment]
The console result displays only the files which have a cognitive complexity higher than the warning threshold by default (10, if I remember well), or by the warning threshold customized in your geneseconfig.json file, just like this : 
![image](https://user-images.githubusercontent.com/63037808/170861199-09ef7eef-4292-486f-9114-89d6529e33a2.png)
Did you try to change this threshold ?

About the possibility to display the results by file and not by method, this functionality is not developed for now, but it would be interesting to do it. If you would like to add it as a new feature of @genese/complexity, it will be a pleasure to help you to do it.

If not, you can simply order the column "filename" and group the results. It may be long if you have a huge project, but possible for middle size projects.

**Comment by skytreader** [comment]
Tweaking the threshold works for me :+1: .

I'll close the issue now but I'd see about addressing my second concern myself. I'll ask for help when I need it, thanks :).
